# copy, update values and rename to config.toml

[accounts.gmail]
default = true
email = "jdoe@gmail.com"
display-name = "John Doe"
downloads-dir = "~/Downloads"

backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "jdoe@gmail.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.raw = "insert_password_here"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "jdoe@gmail.com"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = "insert_password_here"
